site_name: RAiDER API Documentation
site_description:
repo_url: https://github.com/dbekaert/RAiDER
repo_name: RAiDER

nav:
  - Home page: index.md
  - Tutorials:
    - Overview: tutorials.md
    - RAiDER tutorial: https://nbviewer.org/github/dbekaert/RAiDER-docs/blob/main/notebooks/RAiDER_tutorial/RAiDER_tutorial.ipynb" target="_blank
    - raiderStats tutorial: https://nbviewer.org/github/dbekaert/RAiDER-docs/blob/main/notebooks/raiderStats/raiderStats_tutorial.ipynb" target="_blank
    - Downloading GNSS tropospheric delays: https://nbviewer.org/github/dbekaert/RAiDER-docs/blob/main/notebooks/raiderDownloadGNSS/raiderDownloadGNSS_tutorial.ipynb"  target="_blank
    - GNSS delay manipulation with Pandas: https://nbviewer.org/github/dbekaert/RAiDER-docs/blob/main/notebooks/Pandas_tutorial/Pandas_tutorial.ipynb"  target="_blank
  - Weather Model Access: WeatherModels.md
  - Delay Calculation: reference_td.md
  - API Reference: reference.md


theme: 
  name: material

plugins:
  - search
  - macros:
      module_name: docs/macros
  - mkdocstrings:
      handlers:
        python:
          inherited_members: true
